### ISSUE TITLE
clarification about host being the container of the remote apps

### ISSUE THREAD

**Issue by cesarpachon** [sarat9/microfrontends#2]
hello, I am trying to wrap my head aroud this microfrontend concept, I had first understood that the host acts as a shell, a container where the remote components are embed.
But I see the opossite pattern in your code: you are using the host as a shared library repository, and the remotes each one are full-fledged apps.
I wonder if you can explain how to achieve the first effect (host as main container) and render conditionaly the remotes as views depending on the url path, for example. thanks!

**Comment by sarat9** [comment]
Hi @cesarpachon , micro frontends can be structured the way we want to.
The current repo uses a running app as a host and this host acts as your repository for all of the components.
In other scenarios, there could be apps sharing components with each other with no host at all.

In the current repo, we call the repo a host which is also a repository of components because many organizations maintain a storybook and it makes things easier to work, view and update the components in a single platform.

Coming to other terminologies,
Here is a blog with the same WebpackModuleFederation plugin with the app shell way of explanation.
https://dev.to/bitovi/how-to-build-a-micro-frontend-with-webpacks-module-federation-plugin-n41

Also, try going through the below repos of micro frontend components.
-  This uses piral framework to host and run micro-frontends
https://github.com/sarat9/piral-sample-demo

https://piral.io/

- This is a library of web components that we can use as micro frontends across different frameworks
https://github.com/sarat9/cross-ui-web-comp
